### ISSUE TITLE
"fixed" doesn't work

### ISSUE THREAD

**Issue by hanwa929** [JinmiaoChenLab/cytofkit#79]
I'm using "JinmiaoChenLab/cytofkit". As you know, mergeMethod has "ceil", "fixed", "min", "all". But "fixed" doesn't work. 
When I have 2 fcs files (ex. 2000cells and 11000cells), I set "fixed" with fixedNum=10000, I still get only 4000 x 30 data was extracted (This is the same as "min"). I mean a fixed num (specified by fixedNum) of cells aren't sampled with replacement. I made sure other mergeMethods more than "fixed" work as defined. My friend's laptop also shows the same result.
I'd like to extract cells up to fixedNum with replacement.
Have someone faced the same issue? Could you solve it?

**Comment by SamGG** [comment]
Hi!
Correct, there is a bug.Thanks for reporting. 

The code corresponding to the "fixed" strategy is correct. https://github.com/JinmiaoChenLab/cytofkit/blob/c4f93e5d849cf670c3825e5abacd850822c8eca7/R/cytof_preProcess.R#L70-L75
But there is additional code before that lowers fixedNum to the minimum.
https://github.com/JinmiaoChenLab/cytofkit/blob/c4f93e5d849cf670c3825e5abacd850822c8eca7/R/cytof_preProcess.R#L47-L55
This code should be remove (it may have been added as workaround for tSNE, see below).

Nevertheles, I would like to ask you to think about sampling with replacement means. Here is my humble opinion. First, it putting too much weight on an experiment that does not enough events. So I would not do that. Second, tSNE does not like duplicated events unless check_duplicated = FALSE is forced. Third, as a workaround I would add some jittering (aka randomization) to sampled data with replacement, what is not currently implemented in cytofkit. For example I would try to add uniform random numbers from -0.1 to 0.1 to the data once the transformation asinh(x/5) has been applied. -0.1 ~ asinh(0.5/5)-asinh(1/5), 0.1 ~ asinh(1.5/5)-asinh(1/5), ie 0.5 around 1, the lowest positive count.
Best.

**Comment by hanwa929** [comment]
Thank you for quick response.
I'm using cytofkit_GUI(), have never used programing regarding cytofkit.
Could you solve this issue in cytofkit_GUI()?

**Comment by SamGG** [comment]
Being not the developer, I can't not solve it in this repository. I have just push a fix in my repository https://github.com/i-cyto/cytofkit but didn't test it.
Install cytofkit from github using this repository meanwhile it will be fixed here.
```
if(!require(devtools)) install.packages("devtools") # If not already installed
devtools::install_github("i-cyto/cytofkit")
```
The GUI is slightly different (clearer IMHO).
Let me know if this fix solved your problem.

**Comment by SamGG** [comment]
I will setup a data set to test this and let you know. The messages look like warnings, not errors. This sounds like the warnings I added to alert about replacement. So I would say it's correct. I don't know about the missing values during the plot. The duplicate row.names might be a consequence of the replacement. I will look into this. A quick and dirty trick would be to change the identifiers of the sampled events, and therefore to loose the link to the original FCS file. I am not sure this would be a great problem, because nobody really look which events were sampled.

**Comment by hanwa929** [comment]
As you say, this seems to be warning.
Before the warning message, you can look at a described message;
 if (nchar(shape_string[1]) <= 1) {Error: missing value where TRUE/FALSE needed.
I also think the duplicate row.names is a consequence of the replacement.

I understand what you are meaning in the latter half, but I don't know how to do it.
I think the procedure described below is the same as what you mean.
If you can duplicate data and change identifies of the duplicated sample events before analysis, so it would enable to analyze data including duplicated data. But I don't know how to duplicate and change identifiers of the duplicated events in fcs files because I can deal with only fcs files in cytofkit_GUI().

**Comment by SamGG** [comment]
Should be fixed. Just reinstall from i-cyto and start again the shinyApp command.
Let me know.

**Comment by hanwa929** [comment]
It worked, Great!
But I have one issue. The cluster percentages aren't described in csv file.
I attached the picture. Seems like this issue is coming from duplicated data because CMV1a is a duplicated file. And cluster percentages of the remaining two fcs files aren't described although I applied 4 fcs files.
![image0](https://user-images.githubusercontent.com/58058150/69736613-bc3fa980-10e7-11ea-99b1-4f9253a5a0b6.jpeg)

And, you still watch messages described below when you run the analysis even though this may not be so big issue.

if (nchar(shape_string[1]) <= 1) {Error: missing value where TRUE/FALSE needed.
1: (function (fcsFiles, comp = FALSE, transformMethod = c("autoLgcl", で:
One or more FCS files have less events than specified fixedNum
2: (function (fcsFiles, comp = FALSE, transformMethod = c("autoLgcl", で:
using replacement and uniform randomization
3: Removed 13848 rows containing missing values (geom_point).

**Comment by SamGG** [comment]
Right, fix was too easy, there is a price to pay.
Should we compute keeping duplicated cells or removing replicated cells ?

**Comment by SamGG** [comment]
Install and try again ;-) You directly rerun the shiny app and save files again. Verify the exported FCS files, I didn't. The percentage files are correctly formatted, but I didn't check against manual gating.
I have got same 3 errors/warnings as you, but I didn't check yet.

**Comment by hanwa929** [comment]
You changed the setting?
I forced installation because the message described below came up. 
Skipping install of 'cytofkit' from a github remote, the SHA1 (1a1a9ca1) has not changed since last install. 
The result is still the same.
But this may be because I'm not able to update if you update the setting.

**Comment by SamGG** [comment]
Sorry, should be OK right now. https://github.com/i-cyto/cytofkit/commit/b1a7cd64d5599ab96c4b4bbd2169e56c2d6b7d28

**Comment by hanwa929** [comment]
Great, it's perfect!
Thank you so much.
